# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.webconfig:
         class: AppBundle\Twig\Extension\WebConfigExtension
         arguments:
            doctrine: "@doctrine"         
         tags:
            - { name: twig.extension }
